# Generated by Django 3.0.2 on 2020-03-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='test_field',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
